title: TSWoW Wiki
description: TSWoW - WoTLK Modding Unleashed

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: TSWoW
repo_url: 'https://github.com/tswow/tswow-wiki'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: false
hljs_style: github-gist
