title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: TSWoW
repo_url: "https://github.com/tswow/tswow-wiki-new"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
